version: "3.8"

services:
  app:
    image: mcr.microsoft.com/devcontainers/java:1-21-bookworm
    volumes:
      - ..:/workspaces:cached
    working_dir: /workspaces/Password/password-manager
    command: sleep infinity
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: projectdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: